import type { Metadata } from "next";
import Nav from "@/components/Nav";

export const metadata: Metadata = { title: "Portfolio", description: "Selected production AI, RAG, cloud data, and blockchain architecture work." };

const projects = [
  { title: "AI-Enhanced SDLC Platform", role: "AI Solution Architect", challenge: "Introduce AI across software delivery workflows without reducing engineering control or creating disconnected one-off tools.", approach: ["Designed capabilities spanning requirements analysis, code generation, review, testing, and documentation", "Used RAG over internal repositories and technical documentation", "Designed multi-step orchestration for long-running AI tasks", "Defined prompt, guardrail, and evaluation patterns for production use"], stack: "AWS Bedrock, Claude, Step Functions, Lambda, ECS, S3, OpenSearch, Python, APIs, RAG" },
  { title: "Enterprise AI Copilot / RAG Assistant", role: "AI Solution Architect", challenge: "Give users a single natural-language interface across product documentation and structured operational data.", approach: ["Designed agent routing and tool orchestration", "Built the RAG approach for enterprise documentation", "Combined document retrieval with NL-to-SQL access over Databricks / Delta tables", "Defined evaluation for grounding and response usefulness"], stack: "Azure OpenAI, Azure AI Search, Databricks, Delta Lake, LlamaIndex, Python, Streamlit" },
  { title: "Enterprise Data Platform", role: "Data Architect", challenge: "Create a secure, scalable foundation for enterprise ingestion, transformation, governance, and analytics on Azure.", approach: ["Designed Bronze, Silver, and Gold data layers", "Defined ADF and Databricks ingestion / transformation pipelines", "Structured DEV and PRD infrastructure-as-code", "Designed RBAC, private endpoints, managed identities, monitoring, and reporting alignment"], stack: "Azure Data Lake, Databricks, PySpark, Delta Lake, ADF, Azure DevOps, Terraform/Bicep, Power BI" },
  { title: "Blockchain Analytics Platform", role: "AI Architect / CTO", challenge: "Make complex on-chain transaction data explorable through graph analytics and natural-language querying.", approach: ["Designed a graph-oriented model for transactions, addresses, and fund flows", "Added LLM-based natural-language-to-Cypher querying", "Designed blockchain ingestion and processing pipelines", "Led platform architecture, scalability, DevOps, and backend delivery"], stack: "Python, FastAPI, OpenAI, Claude, LangChain, Memgraph, PostgreSQL, ClickHouse, Kafka/Redpanda, Azure", video: "https://www.loom.com/share/4ef89f1952a542a88968cd24578e1f43?sid=49f08f16-52a9-44e4-90d5-74bdd533a30d" },
];

export default function Portfolio() {
  return <main className="min-h-screen bg-[#0f1115] text-[#f4f4f5] font-sans"><Nav />
    <section className="max-w-[1050px] mx-auto px-7 py-16"><p className="eyebrow">SELECTED WORK</p><h1 className="text-5xl leading-tight mb-6">Architecture behind real AI systems.</h1><p className="max-w-3xl text-gray-300 leading-8 text-lg">Selected AI, RAG, data-platform, and blockchain work. Client names are masked where needed; the architecture and responsibilities reflect real delivery experience.</p></section>
    <section className="px-7 pb-16"><div className="max-w-[1050px] mx-auto grid gap-6">{projects.map(p => <article key={p.title} className="card p-7 md:p-8"><div className="flex flex-col md:flex-row md:justify-between gap-5 mb-6"><div><h2 className="text-2xl md:text-3xl mb-2">{p.title}</h2><p className="text-gray-400">{p.role}</p></div>{p.video && <a href={p.video} target="_blank" rel="noreferrer" className="button-primary text-sm w-fit">Watch Loom demo</a>}</div><div className="grid md:grid-cols-[0.8fr_1.2fr] gap-8"><div><h3 className="label">Challenge</h3><p className="text-gray-300 leading-7">{p.challenge}</p></div><div><h3 className="label">Architecture & contribution</h3><ul className="space-y-3 text-gray-300">{p.approach.map(x => <li key={x} className="flex gap-3"><span className="text-gray-600">—</span><span>{x}</span></li>)}</ul></div></div><div className="border-t border-[#252b37] mt-7 pt-5 text-gray-400 leading-7"><span className="text-gray-200 font-semibold">Stack: </span>{p.stack}</div></article>)}</div></section>
    <section className="section"><div className="content flex flex-col md:flex-row md:items-center md:justify-between gap-6"><div><h2 className="text-3xl mb-3">Need senior AI architecture input?</h2><p className="text-gray-400">Start with a focused review, production sprint, or fractional engagement.</p></div><a href="mailto:dmytro.savenkov@gmail.com?subject=AI%20architecture%20project" className="button-primary w-fit">Discuss a project</a></div></section>
  </main>;
}
